names_of_provinces = [
    'A Coruña',
    'Albacete',
    'Alicante',
    'Almería',
    'Araba',
    'Asturias',
    'Ávila',
    'Badajoz',
    'Barcelona',
    'Bizkaia',
    'Burgos',
    'Cáceres',
    'Cádiz',
    'Cantabria',
    'Castellón',
    'Ceuta',
    'Ciudad Real',
    'Córdoba',
    'Cuenca',
    'Gipuzkoa',
    'Girona',
    'Granada',
    'Guadalajara',
    'Huelva',
    'Huesca',
    'Illes Balears',
    'Jaén',
    'La Rioja',
    'Las Palmas',
    'León',
    'Lleida',
    'Lugo',
    'Madrid',
    'Málaga',
    'Melilla',
    'Murcia',
    'Navarra',
    'Ourense',
    'Palencia',
    'Pontevedra',
    'Salamanca',
    'S.Cruz Tenerife',
    'Segovia',
    'Sevilla',
    'Soria',
    'Tarragona',
    'Teruel',
    'Toledo',
    'Valencia',
    'Valladolid',
    'Zamora',
    'Zaragoza']



choice_tramite = ['TRÁMITES OFICINAS DE EXTRANJERÍA', 'TRÁMITES CUERPO NACIONAL DE POLICÍA']

tramites_de_extranjeria = [
    'AUT. DE RESIDENCIA TEMPORAL POR CIRCUNS.EXCEPCIONALES POR ARRAIGO',
    'AUT. DE RESIDENCIA TEMPORAL POR CIRCUNS.EXCEPCIONALES ARRAIGO FAMILIAR',
    'AUTORIZACIÓN DE RESIDENCIA DE MENORES O INCAPACITADOS NACIDOS EN ESPAÑA',
    'AUTORIZACIÓN DE RESIDENCIA TEMPORAL POR REAGRUPACIÓN FAMILIAR',
    'RENOVACIONES DE AUT. DE RESIDENCIA  y/o  AUT. DE RESIDENCIA Y TRABAJO',
    'TARJETA RESIDENCIA DE FAMILIAR NO COMUNITARIO DE CIUDADANO DE LA UNIÓN EUROPEA',
    'Trámite documentación nacionales terceros países familiares de nacionales del Reino Unido (Brexit)',
    'Trámite para la documentación de nacionales del Reino Unido (Brexit)'
]

tramites_de_policia = [
    'Asignación de N.I.E.',
    'AUTORIZACIONES DE REGRESO',
    'POLICIA - RECOGIDA DE TARJETA DE IDENTIDAD DE EXTRANJERO (TIE)',
    'POLICIA - TÍTULOS DE VIAJE',
    'POLICIA- EXPEDICIÓN/RENOVACIÓN DE DOCUMENTOS DE SOLICITANTES DE ASILO',
    'POLICIA- SOLICITUD ASILO',
    'POLICIA-CERTIFICADO DE REGISTRO DE CIUDADANO DE LA U.E.',
    'POLICIA-CERTIFICADOS (DE RESIDENCIA, DE NO RESIDENCIA Y DE CONCORDANCIA)',
    'POLICIA-EXPEDICIÓN DE CARTA DE INVITACIÓN',
    'POLICIA-INFORMACION DE TRÁMITES DE LA COMISARÍA DE POLICIA',
    'POLICIA-TOMA DE HUELLA (EXPEDICIÓN DE TARJETA), RENOVACIÓN DE TARJETA DE LARGA DURACIÓN Y DUPLICADO',
    'POLICÍA - UCRANIA : SOLICITUD PROTECCIÓN TEMPORAL DESPLAZADOS',
    'POLICÍA TARJETA CONFLICTO UCRANIA–ПОЛІЦІЯ -КАРТКА ДЛЯ ПЕРЕМІЩЕНИХ ОСІБ ВНАСЛІДОК КОНФЛІКТУ В УКРАЇНІ',
    'POLICÍA-EXP.TARJETA ASOCIADA AL ACUERDO DE RETIRADA CIUDADANOS BRITÁNICOS Y SUS FAMILIARES (BREXIT)'
]

tramites_all = tramites_de_extranjeria + tramites_de_policia


choice_documents = ['D.N.I.','N.I.E.', 'PASAPORTE']


name_citizenship = [
    'AFGANISTAN',
    'ALBANIA',
    'ALEMANIA',
    'ANDORRA',
    'ANGOLA',
    'ANGUILLA',
    'ANTIGUA Y BARBUDA',
    'ANTILLAS NL.',
    'APATRIDA',
    'ARABIA SAUDI',
    'ARGELIA',
    'ARGENTINA',
    'ARMENIA',
    'ARUBA',
    'AUSTRALIA',
    'AUSTRIA',
    'AZERBAYAN',
    'BAHAMAS',
    'BAHREIN',
    'BANGLADESH',
    'BARBADOS',
    'BELGICA',
    'BELICE',
    'BENIN',
    'BHUTAN',
    'BIELORRUSIA O BELARUS',
    'BOLIVIA',
    'BOSNIA-HERZEGOVINA',
    'BOTSWANA',
    'BRASIL',
    'BRUNEI DARUSSALAM',
    'BULGARIA',
    'BURKINA FASO',
    'BURUNDI',
    'CABO VERDE',
    'CAMBOYA',
    'CAMERUN',
    'CANADA',
    'CENTROAFRICA REPUBLICA',
    'CHAD',
    'CHILE',
    'CHINA',
    'CHIPRE',
    'COLOMBIA',
    'COMORES',
    'CONGO BRAZZAVILLE',
    'COREA, REP. POP. DEMOC.',
    'COREA, REPUBLICA',
    'COSTA DE MARFIL',
    'COSTA RICA',
    'CROACIA',
    'CUBA',
    'DINAMARCA',
    'DJIBOUTI',
    'DOMINICA',
    'DOMINICANA REPUBLICA',
    'ECUADOR',
    'EEUU',
    'EGIPTO',
    'EL SALVADOR',
    'EL VATICANO',
    'EMIRATOS ARABES UNIDOS',
    'ERITREA',
    'ESLOVAQUIA',
    'ESLOVENIA',
    'ESPAÑA',
    'ESTONIA',
    'ETIOPIA',
    'FIDJI',
    'FILIPINAS',
    'FINLANDIA',
    'FRANCIA',
    'GABON',
    'GAMBIA',
    'GEORGIA',
    'GHANA',
    'GRANADA REPUBLICA',
    'GRECIA',
    'GUATEMALA',
    'GUAYANA',
    'GUINEA ECUATORIAL',
    'GUINEA REPUBLICA',
    'GUINEA-BISSAU',
    'HAITI',
    'HOLANDA',
    'HONDURAS',
    'HUNGRIA',
    'INDIA',
    'INDONESIA',
    'IRAK',
    'IRAN',
    'IRLANDA',
    'ISLANDIA',
    'ISLAS MARSCHALL',
    'ISRAEL',
    'ITALIA',
    'JAMAICA',
    'JAPON',
    'JORDANIA',
    'KAZAJSTAN',
    'KENIA',
    'KIRGUISTAN',
    'KIRIBATI',
    'KUWAIT',
    'LAOS',
    'LAS MALDIVAS',
    'LESOTHO',
    'LETONIA',
    'LIBANO',
    'LIBERIA',
    'LIBIA',
    'LIECHTENSTEIN',
    'LITUANIA',
    'LUXEMBURGO',
    'MACAO',
    'MACEDONIA',
    'MADAGASCAR',
    'MALASIA',
    'MALASIA - GRAN BRETAÑA',
    'MALAWI',
    'MALI',
    'MALTA',
    'MARRUECOS',
    'MAURICIO',
    'MAURITANIA',
    'MEJICO',
    'MICRONESIA',
    'MOLDAVIA',
    'MONACO',
    'MONGOLIA',
    'MONTENEGRO',
    'MOZAMBIQUE',
    'MYANMAR',
    'NAMIBIA',
    'NAURU',
    'NEPAL',
    'NICARAGUA',
    'NIGER',
    'NIGERIA',
    'NORUEGA',
    'NUEVA ZELANDA',
    'OMAN',
    'PAKISTAN',
    'PALESTINA EONU',
    'PANAMA',
    'PAPUA NUEVA GUINEA,'
    'PARAGUAY',
    'PERU',
    'POLONIA',
    'PORTUGAL',
    'PUERTO RICO',
    'QATAR',
    'REINO UNIDO',
    'REP. DEMOCRATICA DEL CONGO (EX-ZAIRE)',
    'REPUBLICA CHECA',
    'REUNION-COMO',
    'RUANDA',
    'RUMANIA',
    'RUSIA',
    'SALOMON',
    'SAMOA OCCIDENTAL',
    'SAN CRISTOBAL Y NEVIS',
    'SAN MARINO',
    'SAN VICENTE',
    'SANTA LUCIA',
    'SANTO TOME Y PRINCIPE',
    'SEICHELLES',
    'SENEGAL',
    'SENEGAMBIA',
    'SERBIA',
    'SIERRA LEONA',
    'SINGAPUR',
    'SIRIA',
    'SOMALIA',
    'SRI LANKA',
    'SUDAFRICA',
    'SUDAN',
    'SUECIA',
    'SUIZA',
    'SURINAM',
    'SWAZILANDIA',
    'TADJIKISTAN',
    'TAIWAN',
    'TANZANIA',
    'THAILANDIA',
    'TIMOR ORIENTAL',
    'TOGO',
    'TONGA',
    'TRINIDAD Y TOBAGO',
    'TUNEZ',
    'TURKMENIA',
    'TURQUIA',
    'TUVALU',
    'UCRANIA',
    'UGANDA',
    'URUGUAY',
    'UZBEKISTAN',
    'VANUATU',
    'VENEZUELA',
    'VIETNAM',
    'YEMEN',
    'ZAMBIA',
    'ZIMBABWE']
